# Generated by Django 5.1.1 on 2024-09-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='active',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
